version: 0.2
phases:
  build:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket adriaplu-prod-bucket --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml
  name: PackagedSource


