AWSTemplateFormatVersion: "2010-09-09"
Description: "Serverless application."
Transform: AWS::Serverless-2016-10-31

Resources:
  MyRestfulApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServerlessApi
      EndpointConfiguration: EDGE
      StageName: prod
      Cors:
        AllowMethods: "'GET', 'OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      OpenApiVersion: 3.0.1
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "serverless demo api"
          version: "1.0"
        paths:
          /hello:
            get:
              operationId: getlambda
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                passthroughBehavior: WHEN_NO_MATCH
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations
                payloadFormatVersion: "1.0"
              requestBody:
                content:
                  application/json:
                    schema:
                      type: string
                      format: binary
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Origin:
                      schema:
                        type: string
                    Access-Control-Allow-Methods:
                      schema:
                        type: string
                    Access-Control-Allow-Headers:
                      schema:
                        type: string

  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.handler
      Runtime: python3.7
      FunctionName: serverlessFunction
      CodeUri: src/api/hello.py
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref MyRestfulApi
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes


