AWSTemplateFormatVersion: "2010-09-09"
Description: "Serverless application."
Transform: AWS::Serverless-2016-10-31

Resources:
  MyRestfulApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServerlessApi
      EndpointConfiguration: EDGE
      StageName: prod


  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.handler
      Runtime: python3.7
      FunctionName: serverlessFunction
      CodeUri: src/api/hello.py
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref MyRestfulApi
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent10Minutes


